@echo off
echo Stopping all Node processes...
taskkill /F /IM node.exe /T 2>nul

echo Waiting 3 seconds...
timeout /t 3 /nobreak >nul

echo Deleting .next folder...
if exist .next rmdir /s /q .next

echo Starting dev server...
npm run dev
